version: "2"

services:
  trest:
    container_name: trest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./configs:/configs
      - ./db:/db
    ports:
      - "8001:8001"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always